apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: infrastructure
  labels:
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: spotify/backstage:latest
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 7007
              name: backend
          env:
            - name: NODE_ENV
              value: development
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: infrastructure
  labels:
    app: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: backend
      port: 7007
      targetPort: 7007
  type: ClusterIP 