apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: infrastructure
  labels:
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-content
          configMap:
            name: backstage-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-html
  namespace: infrastructure
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MedinovAI Developer Portal</title>
        <style>
            body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                margin: 0; padding: 40px; background: linear-gradient(135deg, #1e3c72, #2a5298);
                color: white; min-height: 100vh; 
            }
            .container { max-width: 800px; margin: 0 auto; text-align: center; }
            h1 { font-size: 3rem; margin-bottom: 1rem; }
            .subtitle { font-size: 1.2rem; opacity: 0.9; margin-bottom: 2rem; }
            .status { background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 20px 0; }
            .success { color: #4ade80; }
            .info { color: #60a5fa; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 MedinovAI Developer Portal</h1>
            <p class="subtitle">AI-Managed Healthcare Platform Infrastructure</p>
            
            <div class="status">
                <h3 class="success">✅ Kubernetes Cluster: Running</h3>
                <h3 class="success">✅ Infrastructure Namespace: Active</h3>
                <h3 class="success">✅ Backstage Service: Deployed</h3>
            </div>
            
            <div class="status">
                <h3 class="info">🎯 Platform Components</h3>
                <p>• Common Services (MySQL, PostgreSQL, Redis): Ready</p>
                <p>• Security & Monitoring Stack: Configured</p>
                <p>• CI/CD Pipeline: GitHub Actions</p>
                <p>• Secret Management: External Secrets Operator</p>
            </div>
            
            <div class="status">
                <h3 class="info">🔗 Quick Links</h3>
                <p>• <a href="#" style="color: #60a5fa;">Service Catalog</a> | <a href="#" style="color: #60a5fa;">Tech Docs</a> | <a href="#" style="color: #60a5fa;">APIs</a></p>
                <p>• <a href="#" style="color: #60a5fa;">Monitoring</a> | <a href="#" style="color: #60a5fa;">Logs</a> | <a href="#" style="color: #60a5fa;">Metrics</a></p>
            </div>
            
            <p style="margin-top: 40px; opacity: 0.7;">
                Deployed on Kubernetes • Managed by AI Agents • HIPAA Compliant
            </p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: infrastructure
  labels:
    app: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 3000
      targetPort: 80
  type: ClusterIP 