apiVersion: apps/v1
kind: Deployment
metadata:
  name: medinovai-common
  namespace: infrastructure
  labels:
    app: medinovai-common
    version: "v2.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medinovai-common
  template:
    metadata:
      labels:
        app: medinovai-common
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      volumes:
        - name: mysql-data
          emptyDir: {}
        - name: pg-data
          emptyDir: {}
        - name: redis-data
          emptyDir: {}
      containers:
        - name: mysql
          image: mysql:8.4.3  # Latest LTS version
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "medinovai-secure-123"
            - name: MYSQL_DATABASE
              value: "medinovai"
            - name: MYSQL_USER
              value: "medinovai"
            - name: MYSQL_PASSWORD
              value: "medinovai-pass"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 60
            periodSeconds: 30

        - name: postgres
          image: postgres:17.2-alpine  # Latest stable Alpine version
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: POSTGRES_DB
              value: "medinovai"
            - name: POSTGRES_USER
              value: "medinovai"
            - name: POSTGRES_PASSWORD
              value: "medinovai-pass"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - medinovai
                - -d
                - medinovai
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - medinovai
                - -d
                - medinovai
            initialDelaySeconds: 60
            periodSeconds: 30

        - name: redis
          image: redis:7.4.1-alpine  # Latest stable Alpine version
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --requirepass
            - "medinovai-redis-pass"
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - medinovai-redis-pass
                - ping
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - medinovai-redis-pass
                - ping
            initialDelaySeconds: 30
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: medinovai-common
  namespace: infrastructure
  labels:
    app: medinovai-common
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: medinovai-common 