# AI Agent Service Accounts for Thousands of AI Agents
# Each agent type gets its own service account for RBAC

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-orchestrator
  namespace: ai-agents
  labels:
    app: ai-agent-orchestrator
    app.kubernetes.io/name: ai-agent-orchestrator
    app.kubernetes.io/part-of: medinovai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-coding
  namespace: ai-agents
  labels:
    app: ai-agent-coding
    app.kubernetes.io/name: ai-agent-coding
    app.kubernetes.io/part-of: medinovai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-testing
  namespace: ai-agents
  labels:
    app: ai-agent-testing
    app.kubernetes.io/name: ai-agent-testing
    app.kubernetes.io/part-of: medinovai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-security
  namespace: ai-agents
  labels:
    app: ai-agent-security
    app.kubernetes.io/name: ai-agent-security
    app.kubernetes.io/part-of: medinovai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-compliance
  namespace: ai-agents
  labels:
    app: ai-agent-compliance
    app.kubernetes.io/name: ai-agent-compliance
    app.kubernetes.io/part-of: medinovai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-documentation
  namespace: ai-agents
  labels:
    app: ai-agent-documentation
    app.kubernetes.io/name: ai-agent-documentation
    app.kubernetes.io/part-of: medinovai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-discovery
  namespace: ai-agents
  labels:
    app: ai-agent-discovery
    app.kubernetes.io/name: ai-agent-discovery
    app.kubernetes.io/part-of: medinovai 