apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-documentation
  namespace: ai-agents
  labels:
    app: ai-agent-documentation
    app.kubernetes.io/name: ai-agent-documentation
    app.kubernetes.io/part-of: medinovai
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-agent-documentation
  template:
    metadata:
      labels:
        app: ai-agent-documentation
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ai-agent-documentation
      containers:
      - name: ai-agent-documentation
        image: medinovai/ai-agent-documentation:v1.0.0
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 8080
          protocol: TCP
        - name: grpc-api
          containerPort: 9090
          protocol: TCP
        - name: metrics
          containerPort: 9091
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          value: "ai-agent-documentation"
        - name: AGENT_TYPE
          value: "documentation"
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_PORT
          value: "9091"
        - name: HEALTH_PORT
          value: "8081"
        - name: GRPC_PORT
          value: "9090"
        - name: HTTP_PORT
          value: "8080"
        - name: MAX_CONCURRENT_DOCS
          value: "12"
        - name: DOC_GENERATION_TIMEOUT
          value: "1800"
        - name: DOCUMENTATION_FORMATS
          value: "markdown,html,pdf,asciidoc,restructuredtext"
        - name: ENABLE_AUTO_GENERATION
          value: "true"
        - name: ENABLE_DOC_REVIEW
          value: "true"
        - name: ENABLE_DOC_OPTIMIZATION
          value: "true"
        - name: ENABLE_MULTILINGUAL
          value: "true"
        - name: SUPPORTED_LANGUAGES
          value: "en,es,fr,de,ja,zh,ko"
        - name: ENABLE_DIAGRAM_GENERATION
          value: "true"
        - name: ENABLE_CODE_DOCUMENTATION
          value: "true"
        - name: ENABLE_API_DOCUMENTATION
          value: "true"
        - name: ENABLE_USER_GUIDES
          value: "true"
        - name: ENABLE_TECHNICAL_SPECS
          value: "true"
        - name: ENABLE_COMPLIANCE_DOCS
          value: "true"
        - name: DOC_QUALITY_THRESHOLD
          value: "85"
        - name: ENABLE_VERSION_CONTROL
          value: "true"
        - name: ENABLE_COLLABORATION
          value: "true"
        - name: ENABLE_SEARCH_OPTIMIZATION
          value: "true"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: documentation-output
          mountPath: /tmp/documentation
          readOnly: false
        - name: documentation-templates
          mountPath: /etc/documentation/templates
          readOnly: true
        - name: documentation-assets
          mountPath: /etc/documentation/assets
          readOnly: true
      volumes:
      - name: documentation-output
        emptyDir: {}
      - name: documentation-templates
        configMap:
          name: documentation-templates
      - name: documentation-assets
        configMap:
          name: documentation-assets
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-documentation
  namespace: ai-agents
  labels:
    app: ai-agent-documentation
    app.kubernetes.io/name: ai-agent-documentation
    app.kubernetes.io/part-of: medinovai
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http-api
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc-api
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: 9091
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: ai-agent-documentation
  sessionAffinity: None 