apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-compliance
  namespace: ai-agents
  labels:
    app: ai-agent-compliance
    app.kubernetes.io/name: ai-agent-compliance
    app.kubernetes.io/part-of: medinovai
    version: v1.0.0
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-agent-compliance
  template:
    metadata:
      labels:
        app: ai-agent-compliance
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ai-agent-compliance
      containers:
      - name: ai-agent-compliance
        image: medinovai/ai-agent-compliance:v1.0.0
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 8080
          protocol: TCP
        - name: grpc-api
          containerPort: 9090
          protocol: TCP
        - name: metrics
          containerPort: 9091
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          value: "ai-agent-compliance"
        - name: AGENT_TYPE
          value: "compliance"
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_PORT
          value: "9091"
        - name: HEALTH_PORT
          value: "8081"
        - name: GRPC_PORT
          value: "9090"
        - name: HTTP_PORT
          value: "8080"
        - name: MAX_CONCURRENT_AUDITS
          value: "8"
        - name: AUDIT_TIMEOUT
          value: "7200"
        - name: COMPLIANCE_FRAMEWORKS
          value: "fda-21-cfr-part-11,hipaa,gdpr,iso-13485,iec-62304,sox,pci-dss"
        - name: ENABLE_AUDIT_TRAIL
          value: "true"
        - name: ENABLE_COMPLIANCE_MONITORING
          value: "true"
        - name: ENABLE_DOCUMENTATION_GENERATION
          value: "true"
        - name: ENABLE_POLICY_ENFORCEMENT
          value: "true"
        - name: ENABLE_RISK_ASSESSMENT
          value: "true"
        - name: ENABLE_CONTROL_TESTING
          value: "true"
        - name: ENABLE_REPORTING
          value: "true"
        - name: AUDIT_RETENTION_DAYS
          value: "2555"
        - name: COMPLIANCE_REPORT_FORMAT
          value: "pdf,html,json,xml"
        - name: ENABLE_AUTOMATED_REMEDIATION
          value: "true"
        - name: ENABLE_COMPLIANCE_ALERTS
          value: "true"
        - name: COMPLIANCE_ALERT_CHANNELS
          value: "email,slack,webhook,sms"
        - name: ENABLE_DIGITAL_SIGNATURES
          value: "true"
        - name: ENABLE_VERSION_CONTROL
          value: "true"
        - name: ENABLE_CHANGE_MANAGEMENT
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: compliance-reports
          mountPath: /tmp/compliance-reports
          readOnly: false
        - name: audit-logs
          mountPath: /tmp/audit-logs
          readOnly: false
        - name: compliance-config
          mountPath: /etc/compliance/config
          readOnly: true
        - name: compliance-templates
          mountPath: /etc/compliance/templates
          readOnly: true
      volumes:
      - name: compliance-reports
        emptyDir: {}
      - name: audit-logs
        emptyDir: {}
      - name: compliance-config
        configMap:
          name: compliance-agent-config
      - name: compliance-templates
        configMap:
          name: compliance-templates
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-compliance
  namespace: ai-agents
  labels:
    app: ai-agent-compliance
    app.kubernetes.io/name: ai-agent-compliance
    app.kubernetes.io/part-of: medinovai
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http-api
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc-api
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: 9091
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: ai-agent-compliance
  sessionAffinity: None 