apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-agents

resources:
  - ai-agent-orchestrator.yaml
  - ai-agent-coding.yaml
  - ai-agent-testing.yaml
  - ai-agent-security.yaml
  - ai-agent-compliance.yaml
  - ai-agent-documentation.yaml
  - ai-agent-discovery.yaml

commonLabels:
  app.kubernetes.io/name: ai-agents
  app.kubernetes.io/part-of: medinovai
  app.kubernetes.io/version: v1.0.0

commonAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9091"
  prometheus.io/path: "/metrics"

images:
  - name: medinovai/ai-agent-orchestrator
    newTag: v1.0.0
  - name: medinovai/ai-agent-coding
    newTag: v1.0.0
  - name: medinovai/ai-agent-testing
    newTag: v1.0.0
  - name: medinovai/ai-agent-security
    newTag: v1.0.0
  - name: medinovai/ai-agent-compliance
    newTag: v1.0.0
  - name: medinovai/ai-agent-documentation
    newTag: v1.0.0
  - name: medinovai/ai-agent-discovery
    newTag: v1.0.0 